name: kiite
description: An inhouse SNS Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.1
  firebase_storage: ^10.3.3
  mix: ^0.0.5
  google_fonts: ^3.0.1
  flutter_native_splash: ^1.3.2
  visibility_detector: ^0.3.3
  image_picker: ^0.8.5+3
  http: ^0.13.4
  photo_view: ^0.12.0
  device_info_plus: ^3.2.1
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  flutter_linkify: ^5.0.2
  metadata_fetch: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/adaptive_icon.png" # Android用
  adaptive_icon_background: "#E91E63"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "#E91E63"